name: Tag

on:
  release:
    types: [released, prereleased]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            runtime: linux-x64
          - os: ubuntu-24.04-arm
            arch: arm64
            runtime: linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.x.x"

      - name: Publish
        working-directory: src/ConfigSnapperConsole
        run: |
          dotnet publish -r ${{ matrix.runtime }} \
          -p:Version=${{ github.ref_name }} \
          -p:InternalVersion=${{ github.ref_name }} \
          -p:PublishSingleFile=true \
          --self-contained true \
          /p:NativeAot=true \
          -o bin/Release/${{ matrix.runtime }} \
          ConfigSnapperConsole.csproj

      - name: Move to upload directory
        run: |
          mkdir -p upload/${{ matrix.runtime }}
          cp src/ConfigSnapperConsole/bin/Release/${{ matrix.runtime }}/ConfigSnapperConsole upload/${{ matrix.runtime }}/ConfigSnapperConsole

      - name: Rename
        working-directory: upload/${{ matrix.runtime }}
        run: mv ConfigSnapperConsole $(echo ${{ github.event.repository.name }}_${{ github.ref_name }}_${{ matrix.runtime }};)

      - name: Append to release
        run: gh release upload ${{ github.ref_name }} upload/${{ matrix.runtime }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v6
        if: ${{ !github.event.release.prerelease }}
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/matiasg19/configsnapper:latest
            ghcr.io/matiasg19/configsnapper:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            TAG=${{ github.ref_name }}

      - name: Build and push Docker image (prerelease)
        uses: docker/build-push-action@v6
        if: ${{ github.event.release.prerelease }}
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/matiasg19/configsnapper:pre
            ghcr.io/matiasg19/configsnapper:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            TAG=${{ github.ref_name }}