name: Tag

on:
  release:
    types: [released, prereleased]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            runtime: linux-x64
          - os: ubuntu-24.04-arm
            arch: arm64
            runtime: linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"

      - name: Publish
        working-directory: src/ConfigSnapperConsole
        run: dotnet publish -r ${{ matrix.runtime }} -p:Version=${{ github.ref_name }} -p:PublishSingleFile=true --self-contained true -o bin/Release/${{ matrix.runtime }}

      - name: Move to upload directory
        run: |
          mkdir -p upload/${{ matrix.runtime }}
          cp src/ConfigSnapperConsole/bin/Release/${{ matrix.runtime }}/ConfigSnapperConsole upload/${{ matrix.runtime }}/ConfigSnapperConsole

      - name: Rename
        working-directory: upload/${{ matrix.runtime }}
        run: mv ConfigSnapperConsole $(echo ${{ github.event.repository.name }}_${{ github.ref_name }}_${{ matrix.runtime }};)

      - name: Append to release
        run: gh release upload ${{ github.ref_name }} upload/${{ matrix.runtime }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
